discreteMath/urls.py
from django.urls import path

from . import views

app_name = 'discreteMath'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>',views.DetailView.as_view(),name='detail'),
    path('<int:pk>/results',views.ResultsView.as_view(),name='results'),
    path('<int:question_id>/vote',views.vote,name='vote'),
]

problemPractice/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('math/', include('discreteMath.urls')),
    path('admin/', admin.site.urls),
]

discreteMath/models.py
from django.db import models
import datetime
from django.utils import timezone

#should be self-encapsulating, might need to increase text limit
class Question(models.Model):
    question_text = models.CharField(max_length=512)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=7)

#I'd like to make this a fillable form, but static answers will do for now
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.CharField(max_length=512)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

discreteMath/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'discreteMath/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last 3 published questions. not including those set to be published in the future"""
        return Question.objects.filter(pub_date__lte=timezone.now()
                ).order_by('-pub_date')[:3]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'discreteMath/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model=Question
    template_name = 'discreteMath/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request,'discreteMath/detail.html',{
            'question' : question,
            'error_message' : "You didn't select a choice.",
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('discreteMath:results', args=(question.id,)))

discreteMath/templates/discreteMath/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><string>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'discreteMath:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}:w
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}" />
  <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
  {% endfor %}
  <input type="submit" value="Vote" />
</form>

discreteMath/templates/discreteMath/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'discreteMath/style.css' %}" />
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'discreteMath:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No problems are available.</p>
{% endif %}

discreteMath/templates/discreteMath/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'discreteMath:detail' question.id %}">Vote again?</a>